# Generated by Django 5.2.9 on 2026-01-15 07:06

import contents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "file",
                    models.ImageField(
                        upload_to=contents.models.image_upload_path,
                        verbose_name="이미지 파일",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="파일 크기"),
                ),
                ("width", models.IntegerField(default=0, verbose_name="너비")),
                ("height", models.IntegerField(default=0, verbose_name="높이")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드 시간"),
                ),
            ],
            options={
                "verbose_name": "이미지",
                "verbose_name_plural": "이미지들",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "file",
                    models.FileField(
                        upload_to=contents.models.video_upload_path,
                        verbose_name="동영상 파일",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=contents.models.thumbnail_upload_path,
                        verbose_name="썸네일",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="파일 크기"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드 시간"),
                ),
            ],
            options={
                "verbose_name": "동영상",
                "verbose_name_plural": "동영상들",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
