# Generated by Django 5.2.8 on 2026-01-07 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreprocessingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preprocessing_pipeline",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="적용할 전처리 기법들의 순서와 파라미터",
                        verbose_name="전처리 파이프라인",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "준비"),
                            ("processing", "처리 중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="ready",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="진행률 (%)")),
                (
                    "current_step",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="현재 단계"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="시작 시간"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료 시간"
                    ),
                ),
                (
                    "processed_frames",
                    models.IntegerField(default=0, verbose_name="처리된 프레임"),
                ),
                (
                    "total_frames",
                    models.IntegerField(default=0, verbose_name="총 프레임"),
                ),
                (
                    "output_file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="출력 파일 경로"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="에러 메시지"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preprocessing_tasks",
                        to="contents.image",
                        verbose_name="이미지",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preprocessing_tasks",
                        to="contents.video",
                        verbose_name="동영상",
                    ),
                ),
            ],
            options={
                "verbose_name": "전처리 작업",
                "verbose_name_plural": "전처리 작업들",
                "ordering": ["-created_at"],
            },
        ),
    ]
