# Generated by Django 5.2.8 on 2026-01-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preprocess", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preprocessingtask",
            name="current_step",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                null=True,
                verbose_name="현재 단계",
            ),
        ),
    ]
