# Generated by Django 5.2.8 on 2026-01-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preprocess", "0002_alter_preprocessingtask_current_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preprocessingtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "대기 중"),
                    ("processing", "처리 중"),
                    ("completed", "완료"),
                    ("failed", "실패"),
                ],
                default="pending",
                max_length=20,
                verbose_name="상태",
            ),
        ),
    ]
