# Generated by Django 5.2.8 on 2026-01-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preprocess", "0003_alter_preprocessingtask_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preprocessingtask",
            name="error_message",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="에러 메시지"
            ),
        ),
    ]
