# Generated by Django 5.2.8 on 2026-01-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preprocess", "0004_alter_preprocessingtask_error_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preprocessingtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("ready", "준비"),
                    ("pending", "대기 중"),
                    ("processing", "처리 중"),
                    ("completed", "완료"),
                    ("failed", "실패"),
                    ("cancelled", "취소됨"),
                ],
                default="pending",
                max_length=20,
                verbose_name="상태",
            ),
        ),
    ]
