# Generated by Django 5.2.9 on 2026-01-16 02:12

import prephub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PreprocessingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="기법 이름")),
                (
                    "code",
                    models.CharField(
                        help_text="프로그램에서 사용되는 고유 식별자 (예: my_blur)",
                        max_length=50,
                        unique=True,
                        verbose_name="기법 코드",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("edge", "경계 검출"),
                            ("blur", "블러/노이즈 제거"),
                            ("threshold", "임계값 처리"),
                            ("morphology", "형태학적 변환"),
                            ("color", "색상 변환"),
                            ("feature", "특징 검출"),
                            ("enhancement", "이미지 향상"),
                            ("custom", "사용자 정의"),
                        ],
                        default="custom",
                        max_length=20,
                        verbose_name="카테고리",
                    ),
                ),
                (
                    "python_file",
                    models.FileField(
                        blank=True,
                        help_text=".py 파일을 업로드하세요",
                        null=True,
                        upload_to=prephub.models.method_upload_path,
                        verbose_name="Python 파일",
                    ),
                ),
                (
                    "function_name",
                    models.CharField(
                        default="process",
                        help_text="Python 파일 내에서 실행할 함수 이름 (기본: process)",
                        max_length=100,
                        verbose_name="함수 이름",
                    ),
                ),
                (
                    "parameter_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="각 파라미터의 타입, 기본값, 범위 등을 정의",
                        verbose_name="파라미터 스키마",
                    ),
                ),
                (
                    "default_parameters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="기본 파라미터"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "is_builtin",
                    models.BooleanField(
                        default=False,
                        help_text="시스템 기본 제공 기법 (삭제 불가)",
                        verbose_name="내장 기법",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "전처리 기법",
                "verbose_name_plural": "전처리 기법들",
                "ordering": ["category", "name"],
            },
        ),
    ]
