# Generated by Django 5.2.8 on 2026-01-05 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prephub", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PreprocessingTechnique",
            new_name="PreprocessingMethod",
        ),
    ]
