# Generated by Django 5.2.8 on 2026-01-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prephub", "0002_rename_preprocessingtechnique_preprocessingmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="preprocessingmethod",
            name="implementation_code",
            field=models.TextField(
                blank=True,
                help_text="Python 함수 코드 (def process_frame(frame, **params): ...)",
                verbose_name="구현 코드",
            ),
        ),
    ]
