# Generated by Django 5.2.8 on 2026-01-05 07:59

import prephub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prephub", "0003_preprocessingmethod_implementation_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preprocessingmethod",
            name="implementation_code",
        ),
        migrations.AddField(
            model_name="preprocessingmethod",
            name="function_name",
            field=models.CharField(
                default="process",
                help_text="Python 파일 내에서 실행할 함수 이름 (기본: process)",
                max_length=100,
                verbose_name="함수 이름",
            ),
        ),
        migrations.AddField(
            model_name="preprocessingmethod",
            name="python_file",
            field=models.FileField(
                blank=True,
                help_text=".py 파일을 업로드하세요",
                null=True,
                upload_to=prephub.models.method_upload_path,
                verbose_name="Python 파일",
            ),
        ),
        migrations.AlterField(
            model_name="preprocessingmethod",
            name="code",
            field=models.CharField(
                help_text="프로그램에서 사용되는 고유 식별자 (예: my_blur)",
                max_length=50,
                unique=True,
                verbose_name="기법 코드",
            ),
        ),
    ]
