# Generated by Django 5.2.9 on 2026-01-16 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComparisonMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="방법 이름"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="표시 이름"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("feature", "특징점 기반"),
                            ("structural", "구조적 유사도"),
                            ("pixel", "픽셀 차이"),
                            ("histogram", "히스토그램"),
                            ("deep", "딥러닝"),
                            ("optical", "광학 흐름"),
                            ("phase", "위상 상관"),
                            ("color", "색상 기반"),
                        ],
                        max_length=20,
                        verbose_name="카테고리",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "default_params",
                    models.JSONField(
                        default=dict,
                        help_text="예: {'n_features': 1000, 'threshold': 0.75}",
                        verbose_name="기본 파라미터",
                    ),
                ),
                (
                    "param_schema",
                    models.JSONField(
                        default=dict,
                        help_text="UI에서 파라미터 입력 폼을 생성하기 위한 스키마",
                        verbose_name="파라미터 스키마",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                ("order", models.IntegerField(default=0, verbose_name="정렬 순서")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "비교 방법",
                "verbose_name_plural": "비교 방법들",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ComparisonFeatureExtraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extraction_params",
                    models.JSONField(default=dict, verbose_name="추출 파라미터"),
                ),
                ("features_data", models.JSONField(verbose_name="피처 데이터")),
                (
                    "extracted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="추출 시간"),
                ),
                (
                    "processing_time",
                    models.FloatField(default=0.0, verbose_name="처리 시간(초)"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_extractions",
                        to="contents.image",
                        verbose_name="이미지",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="image_compare.comparisonmethod",
                        verbose_name="추출 방법",
                    ),
                ),
            ],
            options={
                "verbose_name": "피처 추출 결과",
                "verbose_name_plural": "피처 추출 결과들",
                "ordering": ["-extracted_at"],
                "indexes": [
                    models.Index(
                        fields=["image", "method"],
                        name="image_compa_image_i_90b82b_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ImageComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="비교 제목"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="비교 설명")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="비교 생성 시간"
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="예: {'n_features': 1000, 'threshold': 0.75, 'visualization_types': ['matches', 'heatmap']}",
                        verbose_name="비교 파라미터",
                    ),
                ),
                (
                    "result_images",
                    models.JSONField(
                        default=list,
                        help_text="예: [{'type': 'matches', 'path': '...'}, {'type': 'heatmap', 'path': '...'}]",
                        verbose_name="결과 이미지 목록",
                    ),
                ),
                (
                    "similarity_scores",
                    models.JSONField(
                        default=dict,
                        help_text="예: {'overall': 0.85, 'feature_match': 0.90, 'color_similarity': 0.80}",
                        verbose_name="유사도 점수",
                    ),
                ),
                (
                    "feature_comparison_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="피처 비교 데이터"
                    ),
                ),
                (
                    "processing_time",
                    models.FloatField(default=0.0, verbose_name="처리 시간(초)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("processing", "처리 중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="비교 상태",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="에러 메시지"),
                ),
                (
                    "comparison_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="image_compare.comparisonmethod",
                        verbose_name="비교 방법",
                    ),
                ),
                (
                    "image_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_first",
                        to="contents.image",
                        verbose_name="첫 번째 이미지",
                    ),
                ),
                (
                    "image_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_second",
                        to="contents.image",
                        verbose_name="두 번째 이미지",
                    ),
                ),
            ],
            options={
                "verbose_name": "이미지 비교",
                "verbose_name_plural": "이미지 비교들",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="image_compa_created_8b69e9_idx"
                    ),
                    models.Index(
                        fields=["status"], name="image_compa_status_a31eb3_idx"
                    ),
                    models.Index(
                        fields=["comparison_method"],
                        name="image_compa_compari_d89eae_idx",
                    ),
                ],
            },
        ),
    ]
