# Generated by Django 5.2.8 on 2026-01-07 02:16

import modelhub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="모델 이름")),
                (
                    "display_name",
                    models.CharField(max_length=200, verbose_name="표시 이름"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "model_type",
                    models.CharField(
                        default="yolo", max_length=50, verbose_name="모델 타입"
                    ),
                ),
                (
                    "version",
                    models.CharField(blank=True, max_length=50, verbose_name="버전"),
                ),
                (
                    "model_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=modelhub.models.default_model_upload_path,
                        verbose_name="모델 파일",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="파일 크기 (bytes)"),
                ),
                (
                    "yolo_version",
                    models.CharField(
                        blank=True,
                        help_text="예: yolov8n.pt, yolov8s.pt",
                        max_length=50,
                        verbose_name="YOLO 버전",
                    ),
                ),
            ],
        ),
    ]
