# Generated by Django 5.2.8 on 2026-01-09 06:49

import django.core.files.storage
import modelhub.models
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="모델 이름")),
                (
                    "display_name",
                    models.CharField(max_length=200, verbose_name="표시 이름"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "model_type",
                    models.CharField(
                        default="yolo", max_length=50, verbose_name="모델 타입"
                    ),
                ),
                (
                    "version",
                    models.CharField(blank=True, max_length=50, verbose_name="버전"),
                ),
                (
                    "model_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location=pathlib.PureWindowsPath(
                                "C:/workspace/VideoTool/models"
                            )
                        ),
                        upload_to=modelhub.models.default_model_upload_path,
                        verbose_name="모델 파일",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="파일 크기 (bytes)"),
                ),
                (
                    "yolo_version",
                    models.CharField(
                        blank=True,
                        help_text="예: yolov8n.pt, yolov8s.pt",
                        max_length=50,
                        verbose_name="YOLO 버전",
                    ),
                ),
                (
                    "classes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="탐지 클래스"
                    ),
                ),
                (
                    "input_size",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="입력 크기"
                    ),
                ),
                (
                    "config",
                    models.JSONField(blank=True, default=dict, verbose_name="설정"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본 모델"),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="사용 횟수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "기본 모델",
                "verbose_name_plural": "기본 모델들",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="모델 이름")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "model_type",
                    models.CharField(
                        default="yolo", max_length=50, verbose_name="모델 타입"
                    ),
                ),
                (
                    "model_file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location=pathlib.PureWindowsPath(
                                "C:/workspace/VideoTool/models"
                            )
                        ),
                        upload_to=modelhub.models.custom_model_upload_path,
                        verbose_name="모델 파일",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="파일 크기 (bytes)"),
                ),
                (
                    "file_format",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="파일 형식"
                    ),
                ),
                (
                    "training_dataset",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="학습 데이터셋"
                    ),
                ),
                (
                    "training_epochs",
                    models.IntegerField(default=0, verbose_name="학습 에포크"),
                ),
                (
                    "performance_metrics",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="성능 지표"
                    ),
                ),
                (
                    "config",
                    models.JSONField(blank=True, default=dict, verbose_name="설정"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="사용 횟수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "커스텀 모델",
                "verbose_name_plural": "커스텀 모델들",
                "ordering": ["-created_at"],
            },
        ),
    ]
