# Generated by Django 6.0.1 on 2026-01-21 05:15

import django.core.files.storage
import django.core.validators
import modelhub.models
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("builtin", "Built-in"),
                            ("upload", "File Upload"),
                            ("git", "Git Repository"),
                            ("huggingface", "HuggingFace"),
                        ],
                        max_length=20,
                        verbose_name="소스",
                    ),
                ),
                (
                    "builtin_preset",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yolov8n", "YOLOv8 Nano (빠름)"),
                            ("yolov8s", "YOLOv8 Small (균형) ⭐"),
                            ("yolov8m", "YOLOv8 Medium (정확)"),
                            ("yolov8l", "YOLOv8 Large (매우 정확)"),
                            ("yolov8x", "YOLOv8 XLarge (최고)"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Built-in 프리셋",
                    ),
                ),
                (
                    "model_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url="/models/",
                            location=pathlib.PureWindowsPath(
                                "C:/workspace/VideoTool/models"
                            ),
                        ),
                        upload_to=modelhub.models.model_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pt", "pth", "onnx", "h5", "pb", "tflite"]
                            )
                        ],
                        verbose_name="모델 파일",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="파일 크기(bytes)"),
                ),
                (
                    "git_url",
                    models.URLField(blank=True, null=True, verbose_name="Git URL"),
                ),
                (
                    "git_branch",
                    models.CharField(
                        blank=True,
                        default="main",
                        max_length=100,
                        verbose_name="Branch",
                    ),
                ),
                (
                    "git_subfolder",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Subfolder"
                    ),
                ),
                (
                    "git_commit_hash",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Commit Hash"
                    ),
                ),
                (
                    "hf_model_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="HF Model ID",
                    ),
                ),
                (
                    "hf_revision",
                    models.CharField(
                        blank=True,
                        default="main",
                        max_length=100,
                        verbose_name="Revision",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="모델 이름")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "task_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("object_detection", "Object Detection"),
                            ("image_classification", "Image Classification"),
                            ("segmentation", "Segmentation"),
                            ("super_resolution", "Super Resolution"),
                            ("image_restoration", "Image Restoration"),
                        ],
                        max_length=50,
                        verbose_name="작업 유형",
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="프레임워크"
                    ),
                ),
                (
                    "architecture",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="아키텍처"
                    ),
                ),
                (
                    "classes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="클래스 목록"
                    ),
                ),
                (
                    "num_classes",
                    models.IntegerField(default=0, verbose_name="클래스 개수"),
                ),
                (
                    "input_size",
                    models.JSONField(
                        blank=True, default=list, verbose_name="입력 크기"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="추가 메타데이터"
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="사용 횟수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "모델",
                "verbose_name_plural": "모델들",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "is_active"],
                        name="modelhub_mo_source_9f5e16_idx",
                    ),
                    models.Index(
                        fields=["task_type"], name="modelhub_mo_task_ty_92cdd8_idx"
                    ),
                ],
            },
        ),
    ]
