# Generated by Django 5.2.9 on 2026-01-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelhub", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="custommodel",
            name="performance_metrics",
        ),
        migrations.RemoveField(
            model_name="custommodel",
            name="training_dataset",
        ),
        migrations.RemoveField(
            model_name="custommodel",
            name="training_epochs",
        ),
        migrations.AddField(
            model_name="custommodel",
            name="accuracy",
            field=models.FloatField(blank=True, null=True, verbose_name="정확도 (%)"),
        ),
        migrations.AddField(
            model_name="custommodel",
            name="author",
            field=models.CharField(blank=True, max_length=100, verbose_name="작성자"),
        ),
        migrations.AddField(
            model_name="custommodel",
            name="classes",
            field=models.JSONField(
                blank=True, default=list, verbose_name="탐지 클래스"
            ),
        ),
        migrations.AddField(
            model_name="custommodel",
            name="dataset_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="데이터셋 이름"
            ),
        ),
        migrations.AddField(
            model_name="custommodel",
            name="framework",
            field=models.CharField(
                blank=True,
                help_text="예: PyTorch, TensorFlow, ONNX",
                max_length=50,
                verbose_name="프레임워크",
            ),
        ),
        migrations.AddField(
            model_name="custommodel",
            name="inference_time",
            field=models.FloatField(
                blank=True, null=True, verbose_name="추론 시간 (ms)"
            ),
        ),
        migrations.AddField(
            model_name="custommodel",
            name="is_validated",
            field=models.BooleanField(default=False, verbose_name="검증됨"),
        ),
        migrations.AddField(
            model_name="custommodel",
            name="map_score",
            field=models.FloatField(blank=True, null=True, verbose_name="mAP 점수"),
        ),
        migrations.AddField(
            model_name="custommodel",
            name="num_classes",
            field=models.IntegerField(blank=True, null=True, verbose_name="클래스 수"),
        ),
        migrations.AddField(
            model_name="custommodel",
            name="precision",
            field=models.FloatField(blank=True, null=True, verbose_name="정밀도 (%)"),
        ),
        migrations.AddField(
            model_name="custommodel",
            name="recall",
            field=models.FloatField(blank=True, null=True, verbose_name="재현율 (%)"),
        ),
        migrations.AddField(
            model_name="custommodel",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="태그"),
        ),
        migrations.AddField(
            model_name="custommodel",
            name="version",
            field=models.CharField(blank=True, max_length=50, verbose_name="버전"),
        ),
        migrations.AlterField(
            model_name="custommodel",
            name="model_type",
            field=models.CharField(
                default="custom",
                help_text="예: yolo, resnet, custom",
                max_length=50,
                verbose_name="모델 타입",
            ),
        ),
    ]
