# Generated by Django 5.2.9 on 2026-01-16 02:12

import django.db.models.deletion
import vision_engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("modelhub", "0001_initial"),
        ("preprocess", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "file",
                    models.ImageField(
                        upload_to=vision_engine.models.image_upload_path,
                        verbose_name="이미지 파일",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="파일 크기"),
                ),
                ("width", models.IntegerField(default=0, verbose_name="너비")),
                ("height", models.IntegerField(default=0, verbose_name="높이")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드 시간"),
                ),
            ],
            options={
                "verbose_name": "이미지",
                "verbose_name_plural": "이미지들",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "file",
                    models.FileField(
                        upload_to=vision_engine.models.video_upload_path,
                        verbose_name="동영상 파일",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=vision_engine.models.thumbnail_upload_path,
                        verbose_name="썸네일",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="파일 크기"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드 시간"),
                ),
            ],
            options={
                "verbose_name": "동영상",
                "verbose_name_plural": "동영상들",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "대기"),
                            ("processing", "처리 중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="ready",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "total_frames",
                    models.IntegerField(default=0, verbose_name="총 프레임"),
                ),
                (
                    "processed_frames",
                    models.IntegerField(default=0, verbose_name="처리된 프레임"),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="진행률 (%)")),
                (
                    "output_file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="결과 파일 경로"
                    ),
                ),
                (
                    "application_data",
                    models.JSONField(
                        blank=True, default=list, verbose_name="모델 적용 결과 데이터"
                    ),
                ),
                (
                    "total_applications",
                    models.IntegerField(default=0, verbose_name="총 탐지 수"),
                ),
                (
                    "application_summary",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="모델 적용 결과 요약"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="에러 메시지"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="시작 시간"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료 시간"
                    ),
                ),
                (
                    "builtin_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="modelhub.builtinmodel",
                        verbose_name="기본 모델",
                    ),
                ),
                (
                    "custom_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="modelhub.custommodel",
                        verbose_name="커스텀 모델",
                    ),
                ),
                (
                    "preprocessing_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="preprocess.preprocessingtask",
                        verbose_name="전처리 작업",
                    ),
                ),
            ],
            options={
                "verbose_name": "모델 적용",
                "verbose_name_plural": "모델 적용들",
                "ordering": ["-created_at"],
            },
        ),
    ]
