# Generated by Django 5.2.9 on 2026-01-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vision_engine", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detection",
            old_name="base_model",
            new_name="builtin_model",
        ),
    ]
