# Generated by Django 5.2.9 on 2026-01-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vision_engine", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "모델 적용",
                "verbose_name_plural": "모델 적용들",
            },
        ),
        migrations.AlterField(
            model_name="application",
            name="application_data",
            field=models.JSONField(
                blank=True, default=list, verbose_name="모델 적용 결과 데이터"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="application_summary",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="모델 적용 결과 요약"
            ),
        ),
    ]
