# Generated by Django 5.2.9 on 2026-01-14 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vision_engine", "0002_rename_base_model_detection_builtin_model"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detection",
            old_name="detection_data",
            new_name="application_data",
        ),
        migrations.RenameField(
            model_name="detection",
            old_name="detection_summary",
            new_name="application_summary",
        ),
        migrations.RenameField(
            model_name="detection",
            old_name="total_detections",
            new_name="total_applications",
        ),
    ]
